configured_endpoints: 506
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/vaif-studio%2Fvaif-studio-bc97f2a7266260faeee5c00a08e55fa9fe4dac538a288b011e282b5aaabf462f.yml
openapi_spec_hash: 0df00c8eab0ddb08d08430cd7a263b41
config_hash: fef75d0feebdccf5006fd10e96afe774
